### PR TITLE
Get and Set Internal Price breaks for a part

### PR DESCRIPTION
**Pull request by rgilham**
Many of my migrated / existing parts do not have supplier purchase prices, I needed to use the average stock price to set the internal price used to calculate the BOM cost. I wrote a script to retrieve and set but needed support in the python library to retrieve and set the internal price.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@rgilham looks like a great addition! A couple of requirements:

- [ ] Address PEP code style issues
- [ ] Add unit testing for the new features

LMK if you want some pointers for the unit testing

**Comment by rgilham** [comment]
Okay I will have to have a look on how to improve and add unit testing.

LMK??

**Comment by SchrodingersGat** [comment]
Have a look at https://github.com/inventree/inventree-python/blob/master/test/test_company.py as a reference

**Comment by SchrodingersGat** [comment]
@rgilham any further work on this one?

**Comment by SchrodingersGat** [comment]
Closed in https://github.com/inventree/inventree-python/pull/84

**Pull request closed without merging**
