### PR TITLE
Added method to fetch category parameter templates

### PR DESCRIPTION
**Pull request by eeintech**
Duplicate of #40 

Linked to inventree/InvenTree#1130

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat Is the automatic build hook broken again?
I don't see this PR being checked in https://travis-ci.org/github/inventree/inventree-python

**Comment by eeintech** [comment]
Looks like it worked for my branch: https://travis-ci.com/github/eeintech/inventree-python/builds/202592598

**Comment by SchrodingersGat** [comment]
It's very slow at the moment but it seems to be working.

What was the reason for duplicating the original PR and re-implementing it here?

**Comment by eeintech** [comment]
I can see this... Is coveralls supposed to be functioning well?

**Comment by SchrodingersGat** [comment]
It is. Maybe switching the coverage tool (in InvenTree) has changed the behaviour here?

**Comment by eeintech** [comment]
@SchrodingersGat I updated the coverage command, it differed for the `coverage` package.

**Comment by SchrodingersGat** [comment]
Nice, thanks for working this out.

**Pull request merged**
