### PR TITLE
Add add_link function to Attachment class

### PR DESCRIPTION
**Pull request by 30350n**
This adds an `add_link` class method to the `Attachment` class, to make it possible to add external link attachments via the python api.

Should I also add a bunch of `addLinkAttachment` functions to `Part`, `Company`, etc. (similar to the `uploadAttachment` methods)?

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@30350n thanks!

Regarding the suggested extra methods - I think there should be a mixing class in `base.py` which these classes inherit, which implements `uploadAttachment` and `uploasdLink` - there is a lot of code duplicated which would be reduced.

**Comment by 30350n** [comment]
Looking at the code, that would have to be some kind of generative mixin though, because the current `Attachment` classes all have different URLs and REQUIRED_KWARGS. I'll see if I can throw something together tomorrow ^^

**Comment by 30350n** [comment]
Here we go, what do you think of this?

**Comment by SchrodingersGat** [comment]
@30350n clean implementation, I like it. Let's see if it passes :)

**Comment by 30350n** [comment]
Looks good now I'd say!

**Comment by 30350n** [comment]
Mind if I bump the version to 0.13.2 so we can get a release for this?

**Comment by SchrodingersGat** [comment]
@30350n happy for you to bump the release and then I'll merge

**Comment by 30350n** [comment]
Done, thanks a lot! :)

**Pull request merged**
