### PR TITLE
Added method to fetch category parameter templates

### PR DESCRIPTION
**Pull request by eeintech**
Linked to https://github.com/inventree/InvenTree/pull/1130

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
https://travis-ci.org/github/inventree/inventree-python

For some reason the travis build is not linking back here. The fixtures need to be updated as the database structure has changed significantly since the last build of inventree-python!

**Comment by eeintech** [comment]
Ouch, I can see that. I'll have to fix this tomorrow, sorry.

**Comment by eeintech** [comment]
@SchrodingersGat What's your thought on style check? `flake8` is flagging most method names:
```
./inventree/order.py:15:10: N802 function name 'getLineItems' should be lowercase
./inventree/order.py:32:10: N802 function name 'getPart' should be lowercase
./inventree/order.py:35:10: N802 function name 'getOrder' should be lowercase
./inventree/order.py:47:10: N802 function name 'getLineItems' should be lowercase
./inventree/order.py:64:10: N802 function name 'getPart' should be lowercase
./inventree/order.py:67:10: N802 function name 'getOrder' should be lowercase
./inventree/part.py:18:10: N802 function name 'getParts' should be lowercase
./inventree/part.py:21:10: N802 function name 'getParentCategory' should be lowercase
./inventree/part.py:27:10: N802 function name 'getChildCategories' should be lowercase
./inventree/part.py:50:10: N802 function name 'getCategory' should be lowercase
./inventree/part.py:54:10: N802 function name 'getTestTemplates' should be lowercase
./inventree/part.py:58:10: N802 function name 'getSupplierParts' should be lowercase
./inventree/part.py:62:10: N802 function name 'getBomItems' should be lowercase
./inventree/part.py:66:10: N802 function name 'isUsedIn' should be lowercase
./inventree/part.py:70:10: N802 function name 'getBuilds' should be lowercase
./inventree/part.py:74:10: N802 function name 'getStockItems' should be lowercase
./inventree/part.py:78:10: N802 function name 'getAttachments' should be lowercase
./inventree/part.py:82:10: N802 function name 'getParameters' should be lowercase
./inventree/part.py:185:10: N802 function name 'generateTestKey' should be lowercase
./inventree/part.py:196:10: N802 function name 'getTestKey' should be lowercase
./inventree/stock.py:15:10: N802 function name 'getStockItems' should be lowercase
./inventree/stock.py:33:10: N802 function name 'getPart' should be lowercase
./inventree/stock.py:37:10: N802 function name 'getAttachments' should be lowercase
./inventree/stock.py:45:10: N802 function name 'uploadAttachment' should be lowercase
./inventree/stock.py:52:10: N802 function name 'getTestResults' should be lowercase
./inventree/stock.py:57:10: N802 function name 'uploadTestResult' should be lowercase
./inventree/stock.py:80:10: N802 function name 'getTestKey' should be lowercase
./inventree/api.py:76:10: N802 function name 'testServer' should be lowercase
./inventree/api.py:116:10: N802 function name 'requestToken' should be lowercase
./inventree/company.py:11:10: N802 function name 'getSuppliedParts' should be lowercase
./inventree/company.py:14:10: N802 function name 'getManufacturedParts' should be lowercase
./inventree/company.py:23:10: N802 function name 'getPriceBreaks' should be lowercase
```

**Comment by SchrodingersGat** [comment]
Changing all those function names would break any existing scripts that use the inventree-python API.

Mixed case is "allowed" but not recommended - https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

I'd suggest we add an exception for rule N802 and move on.

Cheers

**Comment by eeintech** [comment]
Closing this PR as it seems like it does not sync with my branch anymore...

**Pull request closed without merging**
